name: Run tests on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v3
          with:
            java-version: '17'
        - run: gradle wrapper  # Створити wrapper на льоту
        - run: chmod +x ./gradlew
        - run: ./gradlew build